# EquiPath - Exploratory Data Analysis

This notebook explores the College Results 2021 and Affordability Gap AY2022-23 datasets.

In [1]:
import os
import sys

# Run from the repo root so `src` imports and the `data/` paths resolve,
# whether the notebook is launched from the repo root or from notebooks/
if not os.path.isdir('src'):
    os.chdir('..')
assert os.path.isdir('src'), "run this notebook from the repo root or notebooks/"
sys.path.append(os.getcwd())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from src.data_loading import load_college_results, load_affordability_gap, load_merged_data, explore_join_options

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Visualization settings
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

## 1. Explore Join Options

In [2]:
# Explore potential join keys
join_info = explore_join_options()

Loading College Results from cache: data/.cache/college_results.parquet
✓ Loaded 6289 rows and 192 columns from cache
Loading Affordability Gap from cache: data/.cache/affordability_gap.parquet
✓ Loaded 21299 rows and 79 columns from cache

============================================================
Common columns between datasets:
============================================================
  - Institution Name
  - Institution Size Category

============================================================
Potential identifier columns:
============================================================

In College Results:
  - UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION
  - Instructional Expenses GASB per Student
  - Instructional Expenses FASB per FTE
  - Instructional Expenses Per FTE
  - Cost of Attendance for In-State Students Living on Campus
  - Average Cost of Attendance Out-of-State
  - Average Cost of Attendance In-State
  - Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years
  - City of Institution
  - Institutional Category
  - Institution Name
  - Institution Size Category
  - Sector of Institution
  - State of Institution
  - Institution Web Address
  - Institution Type
  - Out-of-State Average Tuition for First-Time, Full-Time Undergraduates
  - Average In-State Tuition for First-Time, Full-Time Undergraduates
  - Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates
  - Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded
  - Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid
  - Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid
  - Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates
  - Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21
  - Asian American or Native American Pacific Islander-Serving Institution (AANAPISI)
  - Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)
  - Historically Black College or University (HBCU)
  - Hispanic-serving Institution (HSI)
  - Instructional Expenditures Per Student
  - Native American Non-Tribal Institution (NANTI)
  - Predominantly Black Institution (PBI)
  - Tribal College or University (TCU)
  - Public Institution GASB Endowment Assets
  - Private not-for-profit or Public Institution FASB Endowment Assets

In Affordability Gap:
  - Institution Name
  - State Abbreviation
  - Sector Name
  - Cost of Attendance: In State, On Campus
  - Cost of Attendance: Out of State
  - Cost of Attendance: In State
  - State Minimum Wage
  - Income Earned from Working 10 Hours a Week at State's Minimum Wage
  - Highest Degree Offered Name
  - Highest Level Offered Name
  - Degree of Localization Name
  - Institution Level Name
  - Institution Level
  - Institution Size Category Name
  - Institution Size Category
  - County Name
  - State
  - State Code (FIPS)
  - Institution Status
  - 2000 Carnegie Classification Name
  - 2015 Carnegie Classification Name
  - 2018 Carnegie Classification Name
  - 2021 Carnegie Classification Name
  - Control of Institution

## 2. Load Individual Datasets

In [3]:
# Load College Results dataset
college_results = load_college_results()
print(f"\nCollege Results shape: {college_results.shape}")
college_results.head()

Loading College Results from cache: data/.cache/college_results.parquet
✓ Loaded 6289 rows and 192 columns from cache

College Results shape: (6289, 192)

,UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION,Number of Bachelor Degrees Grand Total,Number of Bachelor Degrees Total Men,Number of Bachelor Degrees Total Women,Number of Bachelor Degrees White Total,Number of Bachelor Degrees White Men,Number of Bachelor Degrees White Women,Number of Bachelor Degrees American Indian or Alaska Native Men,Number of Bachelor Degrees American Indian or Alaska Native Total,Number of Bachelor Degrees American Indian or Alaska Native Women,Number of Bachelor Degrees Asian Men,Number of Bachelor Degrees Asian Total,Number of Bachelor Degrees Asian Women,Number of Bachelor Degrees Black or African American Men,Number of Bachelor Degrees Black or African American Total,Number of Bachelor Degrees Black or African American Women,Number of Bachelor Degrees Latino Men,Number of Bachelor Degrees Latino Total,Number of Bachelor Degrees Latina Women,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,"Number of Degrees Awarded in Science, Technology, Engineering, and Math",Number of Degrees Awarded in Arts and Humanities,Number of Degrees Awarded in Education,Number of Degrees Awarded in Social Sciences,Number of Degrees Awarded in Health Sciences,Number of Degrees Awarded in Business,Percent of Bachelor Degrees American Indian or Alaska Native Men,Percent of Bachelor Degrees American Indian or Alaska Native Total,Percent of Bachelor Degrees American Indian or Alaska Native Women,Percent of Bachelor Degrees Asian Men,Percent of Bachelor Degrees Asian Total,Percent of Bachelor Degrees Asian Women,Percent of Bachelor Degrees Black or African American Men,Percent of Bachelor Degrees Black or African American Total,Percent of Bachelor Degrees Black or African American Women,Percent of Bachelor Degrees Latino Men,Percent of Bachelor Degrees Latino Total,Percent of Bachelor Degrees Latina Women,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,Percent of Bachelor Degrees Men,Percent of Bachelor Degrees Women,Percent of Bachelor Degrees White Total,Percent of Bachelor Degrees White Men,Percent of Bachelor Degrees White Women,"Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",Percent of Bachelor Degrees Awarded in Arts and Humanities,Percent of Bachelor Degrees Awarded in Education,Percent of Bachelor Degrees Awarded in Social Sciences,Percent of Bachelor Degrees Awarded in Health Sciences,Percent of Bachelor Degrees Awarded in Business,Percent of American Indian or Alaska Native Undergraduates,Percent of Two or More Races Undergraduates,Percent of Asian Undergraduates,Percent of Black or African American Undergraduates,Percent of Latino Undergraduates,Percent of Native Hawaiian or Other Pacific Islander Undergraduates,Percent of White Undergraduates,Percent of Women Undergraduates,Percent of Men Undergraduates,Percent of Nonresident Undergraduates,Percent of Undergraduates Race-Ethnicity Unknown,Percent of Undergraduates Age 25 to 64,"Percent of Full-time, First-time Degree-Seeking Undergraduates",Percent of Undergraduates Enrolled Exclusively in Distance Education Courses,"Percent of First-Time, Full-Time International Undergraduates",Total Enrollment,"Number of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores","Percentage of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores",ACT English - 25th Percentile Score,ACT English - 75th Percentile Score,ACT Math - 25th Percentile Score,ACT Math - 75th Percentile Score,Number of First-Time Degree Certificate Seeking Students Submitting SAT Scores,Percent of First-Time Degree Certificate Seeking Students Submitting SAT Scores,SAT Evidence Based Reading and Writing - 25th Percentile Score,SAT Evidence Based Reading and Writing - 75th Percentile Score,SAT Math - 25th Percentile Score,SAT Math - 75th Percentile Score,Total Percent of Applicants Admitted,Total Percent of Men Admitted,Total Percent of Women Admitted,Bachelor's Degrees Awarded,Number of Students Receiving a Bachelor's Degree,Endowment Assets GASB per Student,Instructional Expenses GASB per Student,Endowment Assets FASB per Student,Instructional Expenses FASB per FTE,Instructional Expenses Per FTE,Bachelor's Degree Graduation Rate Within 4 Years - Total,Bachelor's Degree Graduation Rate Within 5 Years - Total,Bachelor's Degree Graduation Rate Within 6 Years - American Indian or Alaska Native,"Bachelor's Degree Graduation Rate Within 6 Years - Asian, Native Hawaiian, Pacific Islander",Bachelor's Degree Graduation Rate Within 6 Years - Asian,"Bachelor's Degree Graduation Rate Within 6 Years - Black, Non-Latino",Bachelor's Degree Graduation Rate Within 6 Years - Latino,Bachelor's Degree Graduation Rate Within 6 Years - Men,Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Women,Bachelor's Degree Graduation Rate Within 6 Years - White Non-Latino,Transfer Out Rate,Cost of Attendance for In-State Students Living on Campus,Average Cost of Attendance Out-of-State,Average Cost of Attendance In-District,Average Cost of Attendance In-State,"Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years","Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",Number of American Indian or Alaska Native Men,Number of American Indian or Alaska Native Total,Number of American Indian or Alaska Native Women,Number of Asian Men,Number of Asian Total,Number of Asian Women,Number of Black or African American Men,Number of Black or African American Total,Number of Black or African American Women,Number of Latino Men,Number of Latino Total,Number of Latina Women,Number of Native Hawaiian or Other Pacific Islander Men,Number of Native Hawaiian or Other Pacific Islander Total,Number of Native Hawaiian or Other Pacific Islander Women,Number of Men Enrolled,Number of Undergraduates Enrolled,Grand Total of Women Undergraduates Enrolled,Number of White Men Undergraduates Enrolled,Total Number of White Undergraduates Enrolled,Number of White Women Undergraduates Enrolled,Degree Level,Student Status,"First-Time, Full-Time Retention Rate",Student-to-Faculty Ratio,"Reported First-Time, Full-Time Undergraduate Enrollment",Carnegie Classification,City of Institution,Institutional Category,Institution Name,Institution Size Category,Degree of Urbanization,Sector of Institution,State of Institution,LATITUDE,LONGITUDE,Institution Web Address,Institution Type,Open Admissions Policy,"Out-of-State Average Tuition for First-Time, Full-Time Undergraduates","Average In-State Tuition for First-Time, Full-Time Undergraduates","Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded","Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Number of First-Time, Full-Time Undergraduates Awarded Pell Grants","Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants","Average Net Price After Grants, 2018-19","Average Net Price After Grants, 2019-20","Average Net Price After Grants, 2020-21","Average Net Price for Low-Income Students, 2018-19","Average Net Price for Low-Income Students, 2019-20","Average Net Price for Low-Income Students, 2020-21","Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21","Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",Asian American or Native American Pacific Islander-Serving Institution (AANAPISI),"Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)",Cohort Default Rate,Median Debt for Dependent Students,Median Debt of Completers,Historically Black College or University (HBCU),Hispanic-serving Institution (HSI),Median Debt for Independent Students,Instructional Expenditures Per Student,Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Students Working and Not Enrolled 10 Years After Entry,Native American Non-Tribal Institution (NANTI),Predominantly Black Institution (PBI),Percent of Full-Time Faculty,Percent of Part-Time Undergraduates,Tribal College or University (TCU),Public Institution GASB Endowment Assets,Private not-for-profit or Public Institution FASB Endowment Assets,Number of Undergraduates Age 25 and Older,Percent of Undergraduates Age 25 and Older
0,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.000000,11760.000000,11760.000000,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477
1,101435,244.0,103.0,141.0,176.0,70.0,106.0,0.0,2.0,2.0,2.0,2.0,0.0,19.0,38.0,19.0,6.0,12.0,6.0,0.0,0.0,0.0,34.0,0.0,8.0,5.0,3.0,86.0,0.000000,0.008197,0.008197,0.008197,0.008197,0.000000,0.077869,0.155738,0.077869,0.024590,0.049180,0.024590,0.000000,0.000000,0.000000,0.422131,0.577869,0.721311,0.286885,0.434426,0.139344,0.000000,0.032787,0.020492,0.012295,0.352459,0.0,4.0,1.0,20.0,6.0,0.0,66.0,45.0,55.0,0.0,20.0,4.0,30.0,0.0,0.0,844.0,157.0,62.0,20.0,25.0,17.0,24.0,17.0,7.0,510.0,560.0,470.0,510.0,69.0,69.0,70.0,244.0,244.0,NaN,NaN,70008.0,7326.0,7326.0,33.0,41.0,100.0,0.0,0.0,45.0,31.0,39.0,NaN,44.0,52.0,47.0,NaN,40728.0,36908.000000,36908.000000,36908.000000,0.0,40.0,1.0,4.0,3.0,2.0,6.0,4.0,99.0,153.0,54.0,33.0,52.0,19.0,0.0,0.0,0.0,451.0,792.0,341.0,289.0,532.0,243.0,1.0,22.0,72.0,15.0,858.0,31,Montgomery,2,Huntingdon College,1,12,2,AL,32,-86,www.huntingdon.edu/,Private Not-For-Profit Four-Year,2.0,25995.0,25995.0,8854.0,5070.0,12904.0,15688.0,219.0,100.0,3435618.0,87.0,40.0,21738.0,22026.0,23664.0,19380.0,17960.0,19670.0,23664.0,NaN,44.0,19670.0,0.0,0.0,0.100,15208.0,27000.0,0.0,NaN,23002.0,6497.0,44281.0,48806.0,47921.5,0.0,0.0,0.7595,0.1407,0.0,NaN,51910937.0,37.0,0.014700
2,101994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,61.0,1.0,0.0,34.0,61.0,39.0,NaN,NaN,37.0,20.0,5.0,0.0,374.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10843.0,NaN,NaN,10843.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13705.000000,10015.000000,10015.000000,0.0,41.0,0.0,0.0,0.0,1.0,1.0,0.0,25.0,77.0,52.0,0.0,1.0,1.0,0.0,0.0,0.0,74.0,144.0,70.0,45.0,61.0,16.0,1.0,22.0,73.0,12.0,258.0,40,Evergreen,4,Reid State Technical College,1,41,4,AL,31,-87,www.rstc.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,6428.0,4797.0,8043.0,35.0,95.0,281493.0,19.0,51.0,2918.0,1893.0,931.0,3022.0,1350.0,159.0,NaN,12.0,NaN,159.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7854.0,22780.0,27625.0,27937.0,0.0,0.0,0.5313,0.5377,0.0,NaN,NaN,139.0,0.123996
3,102553,1044.0,427.0,617.0,581.0,240.0,341.0,7.0,31.0,24.0,32.0,83.0,51.0,6.0,24.0,18.0,37.0,97.0,60.0,5.0,16.0,11.0,73.0,0.0,0.0,47.0,255.0,194.0,0.006705,0.029693,0.022989,0.030651,0.079502,0.048851,0.005747,0.022989,0.017241,0.035441,0.092912,0.057471,0.004789,0.015326,0.010536,0.409004,0.590996,0.556513,0.229885,0.326628,0.069923,0.000000,0.000000,0.045019,0.244253,0.185824,5.0,10.0,7.0,3.0,8.0,3.0,49.0,61.0,39.0,2.0,6.0,43.0,6.0,49.0,1.0,10845.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,68.0,70.0,1044.0,1039.0,12069.0,13122.0,NaN,NaN,13122.0,15.0,27.0,5.0,31.0,33.0,13.0,31.0,31.0,15.0,32.0,33.0,38.0,16.0,30880.0,43325.333333,26719.333333,26719.333333,2.0,22.0,61.0,174.0,113.0,136.0,371.0,235.0,59.0,125.0,66.0,183.0,377.0,194.0,59.0,136.0,77.0,1803.0,4052.0,2249.0,931.0,1972.0,1041.0,1.0,22.0,69.0,12.0,6995.0,21,Anchorage,2,University of Alaska Anchorage,4,11,1,AK,61,-150,www.uaa.alaska.edu/,Public Four-Year,2.0,23072.0,7224.0,5628.0,5494.0,3943.0,7523.0,583.0,80.0,4385853.0,210.0,29.0,11961.0,11283.0,12816.0,9383.0,8971.0,9450.0,NaN,104.0,NaN,9450.0,0.0,0.0,0.034,9000.0,20500.0,0.0,NaN,14207.0,12307.0,47371.0,48868.0,47921.5,0.0,0.0,0.5181,0.4772,0.0,60842848.0,NaN,4536.0,0.147388
4,102632,144.0,46.0,98.0,92.0,29.0,63.0,2.0,10.0,8.0,2.0,6.0,4.0,0.0,0.0,0.0,3.0,10.0,7.0,0.0,1.0,1.0,16.0,2.0,25.0,21.0,0.0,42.0,0.013889,0.069444,0.055556,0.013889,0.041667,0.027778,0.000000,0.000000,0.000000,0.020833,0.069444,0.048611,0.000000,0.006944,0.006944,0.319444,0.680556,0.638889,0.201389,0.437500,0.111111,0.013889,0.173611,0.145833,0.000000,0.291667,14.0,11.0,3.0,1.0,7.0,2.0,55.0,65.0,35.0,5.0,5.0,50.0,6.0,52.0,1.0,1997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,59.0,55.0,144.0,144.0,7459.0,15362.0,NaN,NaN,15362.0,13.0,27.0,0.0,50.0,33.0,NaN,0.0,35.0,100.0,29.0,26.0,29.0,24.0,20608.0,32680.000000,18544.000000,18544.000000,0.0,28.0,15.0,50.0,35.0,6.0,17.0,11.0,3.0,8.0,5.0,17.0,38.0,21.0,6.0,11.0,5.0,186.0,477.0,291.0,110.0,263.0,153.0,1.0,22.0,65.0,9.0,1005.0,21,Juneau,2,University of Alaska Southeast,2,33,1,AK,58,-135,www.uas.alaska.edu/,Public Four-Year,2.0,22742.0,7121.0,6059.0,3762.0,2929.0,8360.0,87.0,83.0,727299.0,35.0,33.0,11000.0,10506.0,7428.0,9605.0,6590.0,6157.0,NaN,20.0,NaN,6157.0,0.0,1.0,0.051,7500.0,20000.0,0.0,NaN,12467.0,15823.0,40460.0,41243.0,27937.0,1.0,0.0,0.5583,0.5447,0.0,6773153.0,NaN,911.0,0.172832

In [4]:
# Check for key columns in College Results
print("Searching for earnings, debt, and graduation rate columns...\n")

earnings_cols = [col for col in college_results.columns if 'EARN' in col.upper() or 'SALARY' in col.upper() or 'INCOME' in col.upper()]
debt_cols = [col for col in college_results.columns if 'DEBT' in col.upper() or 'LOAN' in col.upper()]
grad_cols = [col for col in college_results.columns if 'GRAD' in col.upper() or 'COMPLET' in col.upper()]
admit_cols = [col for col in college_results.columns if 'ADMIT' in col.upper() or 'ACCEPTANCE' in col.upper()]

print("Earnings-related columns:")
for col in earnings_cols[:10]:
    print(f"  - {col}")

print("\nDebt-related columns:")
for col in debt_cols[:10]:
    print(f"  - {col}")

print("\nGraduation-related columns:")
for col in grad_cols[:10]:
    print(f"  - {col}")
    
print("\nAdmission-related columns:")
for col in admit_cols[:10]:
    print(f"  - {col}")

Searching for earnings, debt, and graduation rate columns...

Earnings-related columns:
  - Average Net Price for Low-Income Students, 2018-19
  - Average Net Price for Low-Income Students, 2019-20
  - Average Net Price for Low-Income Students, 2020-21
  - Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21
  - Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21
  - Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21
  - Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry
  - Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry
  - Median Earnings of Students Working and Not Enrolled 10 Years After Entry

Debt-related columns:
  - Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates
  - Median Debt for Dependent Students
  - Median Debt of Completers
  - Median Debt for Independent Students

Graduation-related columns:
  - Percent of American Indian or Alaska Native Undergraduates
  - Percent of Two or More Races Undergraduates
  - Percent of Asian Undergraduates
  - Percent of Black or African American Undergraduates
  - Percent of Latino Undergraduates
  - Percent of Native Hawaiian or Other Pacific Islander Undergraduates
  - Percent of White Undergraduates
  - Percent of Women Undergraduates
  - Percent of Men Undergraduates
  - Percent of Nonresident Undergraduates

Admission-related columns:
  - Total Percent of Applicants Admitted
  - Total Percent of Men Admitted
  - Total Percent of Women Admitted

In [5]:
# Load Affordability Gap dataset
affordability_gap = load_affordability_gap()
print(f"\nAffordability Gap shape: {affordability_gap.shape}")
affordability_gap.head()

Loading Affordability Gap from cache: data/.cache/affordability_gap.parquet
✓ Loaded 21299 rows and 79 columns from cache

Affordability Gap shape: (21299, 79)

,Unit ID,Institution Name,City,State Abbreviation,Sector Name,Sector,MSI Status,MSI Type,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,Average Work Study Award,"Cost of Attendance: In State, On Campus",Cost of Attendance: Out of State,Cost of Attendance: In District,Cost of Attendance: In State,Annual Income Estimate,Student Family Earnings Ceiling,State Minimum Wage,Income Earned from Working 10 Hours a Week at State's Minimum Wage,Net Price,Affordability Gap (net price minus income earned working 10 hrs at min wage),Weekly Hours to Close Gap,100% TTD Affordability Gap,150% TTD Affordability Gap,CPI Index,Monthly Center-Based Child Care Cost,Annual Center-Based Child Care Cost,Adjusted Monthly Center-Based Child Care Cost,Monthly Home-Based Child Care Cost,Adjusted Monthly Home-Based Child Care Cost,Annual Home-Based Child Care Cost,Student Parent Affordability Gap: Center-Based Care,Student Parent Affordability Gap: Home-Based Care,Weekly Hours to Close Gap: Center-Based Care,Weekly Hours to Close Gap: Home-Based Care,100% TTD Student Parent Affordability Gap: Center-Based Care,100% TTD Student Parent Affordability Gap: Home-Based Care,150% TTD Student Parent Affordability Gap: Center-Based Care,150% TTD Student Parent Affordability Gap: Home-Based Care,Adjusted Annual Home-Based Child Care Cost,Adjusted Annual Center-Based Child Care Cost,Highest Degree Offered Name,Highest Degree Offered,Highest Level Offered Name,Highest Level Offered,Combined Statistical Area,Degree of Localization Name,Degree of Localization,Institution Level Name,Institution Level,Institution Size Category Name,Institution Size Category,County Name,Zip Code,State,State Code (FIPS),Latitude,Longitude,Region,Region #,Sub Region,Sub Region #,Admissions Website,Institution Status,2000 Carnegie Classification Name,2000 Carnegie Classification,2015 Carnegie Classification Name,2015 Carnegie Classification,2018 Carnegie Classification Name,2018 Carnegie Classification,2021 Carnegie Classification Name,2021 Carnegie Classification,County Code,Control of Institution
0,371928,Modern Technology School,Fountain Valley,CA,"Private for-profit, 2-year",6,1.0,nan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3040.0,nan,NaN,NaN,NaN,7000.0,30000.0,14.00,140.0,22711.0,15711.0,22.4,31422.0,47133.0,1.08,1665.2,19982.4,1795.42,1522.8,1641.88,18273.6,37256.02,35413.60,53.22,50.59,74512.04,70827.20,149024.08,141654.40,19702.56,21545.04,Non-degree granting,0,"At least 2, but less than 4 academic yrs",4,348,City: Small,13,At least 2 but less than 4 years,2,"Under 1,000",1,Orange County,92708-9821,California,6,33.72,-117.92,West,4.0,Pacific Division,9.0,https://www.mtschool.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,6059,3
1,369668,Central Pennsylvania Institute of Science and ...,Pleasant Gap,PA,"Public, 2-year",4,1.0,nan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1597.0,nan,NaN,NaN,NaN,3625.0,30000.0,7.25,72.5,9184.0,5559.0,15.3,11118.0,16677.0,1.08,1392.8,16713.6,1501.72,1233.6,1330.07,14803.2,23579.60,21519.81,65.05,59.36,47159.20,43039.62,94318.40,86079.24,15960.84,18020.64,Associate's degree,40,Associate's degree,3,524,Rural: Fringe,41,At least 2 but less than 4 years,2,"Under 1,000",1,Centre County,16823,Pennsylvania,42,40.88,-77.74,Northeast,1.0,Middle Atlantic Division,2.0,,A,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,Special Focus Two-Year: Technical Professions,11,42027,1
2,369516,Bryan University,Springfield,MO,"Private for-profit, 4-year or above",3,1.0,nan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2165.0,.,15693.0,15693.0,15693.0,5150.0,30000.0,10.30,103.0,21316.0,16166.0,31.4,64664.0,96996.0,1.08,1110.0,13320.0,1196.80,1258.8,1357.24,15105.6,30527.62,32452.86,59.28,63.02,122110.48,129811.44,183165.72,194717.16,16286.88,14361.60,Master's degree,20,Master's degree,7,-2,City: Midsize,12,Four or more years,1,"Under 1,000",1,Greene County,65804,Missouri,29,37.14,-93.25,Midwest,2.0,West North Central Division,4.0,www.bryanu.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,29077,3
3,164492,Anna Maria College,Paxton,MA,"Private not-for-profit, 4-year or above",2,1.0,nan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,63374,55501.0,55501.0,55501.0,6750.0,30000.0,13.50,135.0,24807.0,18057.0,26.8,72228.0,108342.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,42940.13,38660.11,63.62,57.27,171760.52,154640.44,257640.78,231960.66,20603.16,24883.08,Master's degree,20,Post-master's certificate,8,148,Rural: Fringe,41,Four or more years,1,"1,000 - 4,999",2,Worcester County,01612-1198,Massachusetts,25,42.33,-71.92,Northeast,1.0,New England Division,1.0,www.annamaria.edu/admission,A,Masters Colleges and Universities I,21,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,25027,2
4,164465,Amherst College,Amherst,MA,"Private not-for-profit, 4-year or above",2,1.0,nan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,87640,81787.0,81787.0,81787.0,6750.0,30000.0,13.50,135.0,1888.0,-4862.0,-7.2,-19448.0,-29172.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,20021.13,15741.11,29.66,23.32,80084.52,62964.44,120126.78,94446.66,20603.16,24883.08,Bachelor's degree,30,Bachelor's degree,5,-2,Suburb: Large,21,Four or more years,1,"1,000 - 4,999",2,Hampshire County,01002-5000,Massachusetts,25,42.37,-72.52,Northeast,1.0,New England Division,1.0,www.amherst.edu/admission/,A,Baccalaureate Colleges--Liberal Arts,31,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,25015,2

In [6]:
# Check for key columns in Affordability Gap
print("Searching for affordability and cost columns...\n")

cost_cols = [col for col in affordability_gap.columns if 'COST' in col.upper() or 'PRICE' in col.upper()]
gap_cols = [col for col in affordability_gap.columns if 'GAP' in col.upper()]
parent_cols = [col for col in affordability_gap.columns if 'PARENT' in col.upper()]

print("Cost-related columns:")
for col in cost_cols:
    print(f"  - {col}")

print("\nGap-related columns:")
for col in gap_cols:
    print(f"  - {col}")
    
print("\nParent-related columns:")
for col in parent_cols:
    print(f"  - {col}")

Searching for affordability and cost columns...

Cost-related columns:
  - Cost of Attendance: In State, On Campus
  - Cost of Attendance: Out of State
  - Cost of Attendance: In District
  - Cost of Attendance: In State
  - Net Price
  - Affordability Gap (net price minus income earned working 10 hrs at min wage)
  - Monthly Center-Based Child Care Cost
  - Annual Center-Based Child Care Cost
  - Adjusted Monthly Center-Based Child Care Cost
  - Monthly Home-Based Child Care Cost
  - Adjusted Monthly Home-Based Child Care Cost
  - Annual Home-Based Child Care Cost
  - Adjusted Annual Home-Based Child Care Cost
  - Adjusted Annual Center-Based Child Care Cost

Gap-related columns:
  - Affordability Gap (net price minus income earned working 10 hrs at min wage)
  - Weekly Hours to Close Gap
  - 100% TTD Affordability Gap
  - 150% TTD Affordability Gap
  - Student Parent Affordability Gap: Center-Based Care
  - Student Parent Affordability Gap: Home-Based Care
  - Weekly Hours to Close Gap: Center-Based Care
  - Weekly Hours to Close Gap: Home-Based Care
  - 100% TTD Student Parent Affordability Gap: Center-Based Care
  - 100% TTD Student Parent Affordability Gap: Home-Based Care
  - 150% TTD Student Parent Affordability Gap: Center-Based Care
  - 150% TTD Student Parent Affordability Gap: Home-Based Care

Parent-related columns:
  - Student Parent Affordability Gap: Center-Based Care
  - Student Parent Affordability Gap: Home-Based Care
  - 100% TTD Student Parent Affordability Gap: Center-Based Care
  - 100% TTD Student Parent Affordability Gap: Home-Based Care
  - 150% TTD Student Parent Affordability Gap: Center-Based Care
  - 150% TTD Student Parent Affordability Gap: Home-Based Care

## 3. Merge Datasets

In [7]:
# Attempt merge on Institution Name
# Note: This may need adjustment based on data quality
merged_df = load_merged_data(join_key='Institution Name')
print(f"\nMerged dataset shape: {merged_df.shape}")
merged_df.head()

Loading merged data from cache...
✓ Loaded 21528 rows and 270 columns from cache

Merged dataset shape: (21528, 270)

,UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION,Number of Bachelor Degrees Grand Total,Number of Bachelor Degrees Total Men,Number of Bachelor Degrees Total Women,Number of Bachelor Degrees White Total,Number of Bachelor Degrees White Men,Number of Bachelor Degrees White Women,Number of Bachelor Degrees American Indian or Alaska Native Men,Number of Bachelor Degrees American Indian or Alaska Native Total,Number of Bachelor Degrees American Indian or Alaska Native Women,Number of Bachelor Degrees Asian Men,Number of Bachelor Degrees Asian Total,Number of Bachelor Degrees Asian Women,Number of Bachelor Degrees Black or African American Men,Number of Bachelor Degrees Black or African American Total,Number of Bachelor Degrees Black or African American Women,Number of Bachelor Degrees Latino Men,Number of Bachelor Degrees Latino Total,Number of Bachelor Degrees Latina Women,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,"Number of Degrees Awarded in Science, Technology, Engineering, and Math",Number of Degrees Awarded in Arts and Humanities,Number of Degrees Awarded in Education,Number of Degrees Awarded in Social Sciences,Number of Degrees Awarded in Health Sciences,Number of Degrees Awarded in Business,Percent of Bachelor Degrees American Indian or Alaska Native Men,Percent of Bachelor Degrees American Indian or Alaska Native Total,Percent of Bachelor Degrees American Indian or Alaska Native Women,Percent of Bachelor Degrees Asian Men,Percent of Bachelor Degrees Asian Total,Percent of Bachelor Degrees Asian Women,Percent of Bachelor Degrees Black or African American Men,Percent of Bachelor Degrees Black or African American Total,Percent of Bachelor Degrees Black or African American Women,Percent of Bachelor Degrees Latino Men,Percent of Bachelor Degrees Latino Total,Percent of Bachelor Degrees Latina Women,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,Percent of Bachelor Degrees Men,Percent of Bachelor Degrees Women,Percent of Bachelor Degrees White Total,Percent of Bachelor Degrees White Men,Percent of Bachelor Degrees White Women,"Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",Percent of Bachelor Degrees Awarded in Arts and Humanities,Percent of Bachelor Degrees Awarded in Education,Percent of Bachelor Degrees Awarded in Social Sciences,Percent of Bachelor Degrees Awarded in Health Sciences,Percent of Bachelor Degrees Awarded in Business,Percent of American Indian or Alaska Native Undergraduates,Percent of Two or More Races Undergraduates,Percent of Asian Undergraduates,Percent of Black or African American Undergraduates,Percent of Latino Undergraduates,Percent of Native Hawaiian or Other Pacific Islander Undergraduates,Percent of White Undergraduates,Percent of Women Undergraduates,Percent of Men Undergraduates,Percent of Nonresident Undergraduates,Percent of Undergraduates Race-Ethnicity Unknown,Percent of Undergraduates Age 25 to 64,"Percent of Full-time, First-time Degree-Seeking Undergraduates",Percent of Undergraduates Enrolled Exclusively in Distance Education Courses,"Percent of First-Time, Full-Time International Undergraduates",Total Enrollment,"Number of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores","Percentage of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores",ACT English - 25th Percentile Score,ACT English - 75th Percentile Score,ACT Math - 25th Percentile Score,ACT Math - 75th Percentile Score,Number of First-Time Degree Certificate Seeking Students Submitting SAT Scores,Percent of First-Time Degree Certificate Seeking Students Submitting SAT Scores,SAT Evidence Based Reading and Writing - 25th Percentile Score,SAT Evidence Based Reading and Writing - 75th Percentile Score,SAT Math - 25th Percentile Score,SAT Math - 75th Percentile Score,Total Percent of Applicants Admitted,Total Percent of Men Admitted,Total Percent of Women Admitted,Bachelor's Degrees Awarded,Number of Students Receiving a Bachelor's Degree,Endowment Assets GASB per Student,Instructional Expenses GASB per Student,Endowment Assets FASB per Student,Instructional Expenses FASB per FTE,Instructional Expenses Per FTE,Bachelor's Degree Graduation Rate Within 4 Years - Total,Bachelor's Degree Graduation Rate Within 5 Years - Total,Bachelor's Degree Graduation Rate Within 6 Years - American Indian or Alaska Native,"Bachelor's Degree Graduation Rate Within 6 Years - Asian, Native Hawaiian, Pacific Islander",Bachelor's Degree Graduation Rate Within 6 Years - Asian,"Bachelor's Degree Graduation Rate Within 6 Years - Black, Non-Latino",Bachelor's Degree Graduation Rate Within 6 Years - Latino,Bachelor's Degree Graduation Rate Within 6 Years - Men,Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Women,Bachelor's Degree Graduation Rate Within 6 Years - White Non-Latino,Transfer Out Rate,Cost of Attendance for In-State Students Living on Campus,Average Cost of Attendance Out-of-State,Average Cost of Attendance In-District,Average Cost of Attendance In-State,"Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years","Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",Number of American Indian or Alaska Native Men,Number of American Indian or Alaska Native Total,Number of American Indian or Alaska Native Women,Number of Asian Men,Number of Asian Total,Number of Asian Women,Number of Black or African American Men,Number of Black or African American Total,Number of Black or African American Women,Number of Latino Men,Number of Latino Total,Number of Latina Women,Number of Native Hawaiian or Other Pacific Islander Men,Number of Native Hawaiian or Other Pacific Islander Total,Number of Native Hawaiian or Other Pacific Islander Women,Number of Men Enrolled,Number of Undergraduates Enrolled,Grand Total of Women Undergraduates Enrolled,Number of White Men Undergraduates Enrolled,Total Number of White Undergraduates Enrolled,Number of White Women Undergraduates Enrolled,Degree Level,Student Status,"First-Time, Full-Time Retention Rate",Student-to-Faculty Ratio,"Reported First-Time, Full-Time Undergraduate Enrollment",Carnegie Classification,City of Institution,Institutional Category,Institution Name,Institution Size Category_CR,Degree of Urbanization,Sector of Institution,State of Institution,LATITUDE,LONGITUDE,Institution Web Address,Institution Type,Open Admissions Policy,"Out-of-State Average Tuition for First-Time, Full-Time Undergraduates","Average In-State Tuition for First-Time, Full-Time Undergraduates","Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded","Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Number of First-Time, Full-Time Undergraduates Awarded Pell Grants","Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants","Average Net Price After Grants, 2018-19","Average Net Price After Grants, 2019-20","Average Net Price After Grants, 2020-21","Average Net Price for Low-Income Students, 2018-19","Average Net Price for Low-Income Students, 2019-20","Average Net Price for Low-Income Students, 2020-21","Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21","Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",Asian American or Native American Pacific Islander-Serving Institution (AANAPISI),"Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)",Cohort Default Rate,Median Debt for Dependent Students,Median Debt of Completers,Historically Black College or University (HBCU),Hispanic-serving Institution (HSI),Median Debt for Independent Students,Instructional Expenditures Per Student,Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Students Working and Not Enrolled 10 Years After Entry,Native American Non-Tribal Institution (NANTI),Predominantly Black Institution (PBI),Percent of Full-Time Faculty,Percent of Part-Time Undergraduates,Tribal College or University (TCU),Public Institution GASB Endowment Assets,Private not-for-profit or Public Institution FASB Endowment Assets,Number of Undergraduates Age 25 and Older,Percent of Undergraduates Age 25 and Older,Unit ID,City,State Abbreviation,Sector Name,Sector,MSI Status,MSI Type,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,Average Work Study Award,"Cost of Attendance: In State, On Campus",Cost of Attendance: Out of State,Cost of Attendance: In District,Cost of Attendance: In State,Annual Income Estimate,Student Family Earnings Ceiling,State Minimum Wage,Income Earned from Working 10 Hours a Week at State's Minimum Wage,Net Price,Affordability Gap (net price minus income earned working 10 hrs at min wage),Weekly Hours to Close Gap,100% TTD Affordability Gap,150% TTD Affordability Gap,CPI Index,Monthly Center-Based Child Care Cost,Annual Center-Based Child Care Cost,Adjusted Monthly Center-Based Child Care Cost,Monthly Home-Based Child Care Cost,Adjusted Monthly Home-Based Child Care Cost,Annual Home-Based Child Care Cost,Student Parent Affordability Gap: Center-Based Care,Student Parent Affordability Gap: Home-Based Care,Weekly Hours to Close Gap: Center-Based Care,Weekly Hours to Close Gap: Home-Based Care,100% TTD Student Parent Affordability Gap: Center-Based Care,100% TTD Student Parent Affordability Gap: Home-Based Care,150% TTD Student Parent Affordability Gap: Center-Based Care,150% TTD Student Parent Affordability Gap: Home-Based Care,Adjusted Annual Home-Based Child Care Cost,Adjusted Annual Center-Based Child Care Cost,Highest Degree Offered Name,Highest Degree Offered,Highest Level Offered Name,Highest Level Offered,Combined Statistical Area,Degree of Localization Name,Degree of Localization,Institution Level Name,Institution Level,Institution Size Category Name,Institution Size Category_AG,County Name,Zip Code,State,State Code (FIPS),Latitude,Longitude,Region,Region #,Sub Region,Sub Region #,Admissions Website,Institution Status,2000 Carnegie Classification Name,2000 Carnegie Classification,2015 Carnegie Classification Name,2015 Carnegie Classification,2018 Carnegie Classification Name,2018 Carnegie Classification,2021 Carnegie Classification Name,2021 Carnegie Classification,County Code,Control of Institution
0,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.0,11760.0,11760.0,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477,101301,Selma,AL,"Public, 2-year",4,0.0,PBI,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1936.0,.,17593.0,15053.0,15053.0,3625.0,30000.0,7.25,72.5,497.0,-3128.0,-8.6,-6256.0,-9384.0,1.08,1023.2,12278.4,1103.21,986.4,1063.54,11836.8,10110.57,9634.44,27.89,26.58,20221.14,19268.88,40442.28,38537.76,12762.48,13238.52,Associate's degree,40,Associate's degree,3,388,Town: Distant,32,At least 2 but less than 4 years,2,"1,000 - 4,999",2,Dallas County,36702-2808,Alabama,1,32.45,-87.01,South,3.0,East South Central Division,6.0,https://www.wccs.edu/admissions/student-admiss...,A,Associates Colleges,40,Associate's Colleges: High Career & Technical-...,9,Associate's Colleges: Mixed Transfer/Career & ...,5,Associate's Colleges: Mixed Transfer/Career & ...,5,1047,1
1,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.0,11760.0,11760.0,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477,101301,Selma,AL,"Public, 2-year",4,0.0,PBI,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1936.0,.,17593.0,15053.0,15053.0,3625.0,48000.0,7.25,72.5,1645.0,-1980.0,-5.5,-3960.0,-5940.0,1.08,1023.2,12278.4,1103.21,986.4,1063.54,11836.8,11258.57,10782.44,31.06,29.74,22517.14,21564.88,45034.28,43129.76,12762.48,13238.52,Associate's degree,40,Associate's degree,3,388,Town: Distant,32,At least 2 but less than 4 years,2,"1,000 - 4,999",2,Dallas County,36702-2808,Alabama,1,32.45,-87.01,South,3.0,East South Central Division,6.0,https://www.wccs.edu/admissions/student-admiss...,A,Associates Colleges,40,Associate's Colleges: High Career & Technical-...,9,Associate's Colleges: Mixed Transfer/Career & ...,5,Associate's Colleges: Mixed Transfer/Career & ...,5,1047,1
2,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.0,11760.0,11760.0,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477,101301,Selma,AL,"Public, 2-year",4,0.0,PBI,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1936.0,.,17593.0,15053.0,15053.0,3625.0,75000.0,7.25,72.5,3753.0,128.0,0.4,256.0,384.0,1.08,1023.2,12278.4,1103.21,986.4,1063.54,11836.8,13366.57,12890.44,36.87,35.56,26733.14,25780.88,53466.28,51561.76,12762.48,13238.52,Associate's degree,40,Associate's degree,3,388,Town: Distant,32,At least 2 but less than 4 years,2,"1,000 - 4,999",2,Dallas County,36702-2808,Alabama,1,32.45,-87.01,South,3.0,East South Central Division,6.0,https://www.wccs.edu/admissions/student-admiss...,A,Associates Colleges,40,Associate's Colleges: High Career & Technical-...,9,Associate's Colleges: Mixed Transfer/Career & ...,5,Associate's Colleges: Mixed Transfer/Career & ...,5,1047,1
3,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.0,11760.0,11760.0,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477,101301,Selma,AL,"Public, 2-year",4,0.0,PBI,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1936.0,.,17593.0,15053.0,15053.0,3625.0,110000.0,7.25,72.5,8060.0,4435.0,12.2,8870.0,13305.0,1.08,1023.2,12278.4,1103.21,986.4,1063.54,11836.8,17673.57,17197.44,48.75,47.44,35347.14,34394.88,70694.28,68789.76,12762.48,13238.52,Associate's degree,40,Associate's degree,3,388,Town: Distant,32,At least 2 but less than 4 years,2,"1,000 - 4,999",2,Dallas County,36702-2808,Alabama,1,32.45,-87.01,South,3.0,East South Central Division,6.0,https://www.wccs.edu/admissions/student-admiss...,A,Associates Colleges,40,Associate's Colleges: High Career & Technical-...,9,Associate's Colleges: Mixed Transfer/Career & ...,5,Associate's Colleges: Mixed Transfer/Career & ...,5,1047,1

In [8]:
# Check data types and missing values
print("\nData types and missing values:")
print("="*60)
info_df = pd.DataFrame({
    'dtype': merged_df.dtypes,
    'missing': merged_df.isnull().sum(),
    'missing_pct': (merged_df.isnull().sum() / len(merged_df) * 100).round(2)
})
info_df[info_df['missing'] > 0].sort_values('missing_pct', ascending=False)

Data types and missing values:
============================================================

,dtype,missing,missing_pct
Hispanic-serving Institution (HSI),float64,21528,100.00
Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,float64,17887,83.09
ACT Math - 25th Percentile Score,float64,16915,78.57
ACT Math - 75th Percentile Score,float64,16915,78.57
ACT English - 25th Percentile Score,float64,16910,78.55
...,...,...,...
Income Earned from Working 10 Hours a Week at State's Minimum Wage,float64,9,0.04
State Minimum Wage,float64,9,0.04
Annual Income Estimate,float64,9,0.04
Open Admissions Policy,float64,9,0.04
Average Work Study Award,float64,5,0.02

## 4. Identify Key Metrics Columns

Based on the implementation plan, we need to identify:
- Median earnings (10-year)
- Median debt
- Net price
- Affordability gap (standard and parent)
- Graduation rates by race
- Admission rate

In [9]:
# Display sample values for key metric candidates
print("Sample values for potential key metrics:\n")
print("="*60)

# Show a few rows with selected columns (adjust column names as needed)
# This will help us identify the right columns to use
merged_df.info()

Sample values for potential key metrics:

============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21528 entries, 0 to 21527
Columns: 270 entries, UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION to Control of Institution
dtypes: float64(221), int64(23), object(26)
memory usage: 44.3+ MB

## 5. Data Quality Checks

In [10]:
# Check for duplicates
print(f"Number of duplicate rows: {merged_df.duplicated().sum()}")
print(f"Number of duplicate institution names: {merged_df['Institution Name'].duplicated().sum()}")

Number of duplicate rows: 0
Number of duplicate institution names: 15624

In [11]:
# Check distribution of institutions by state
if 'State of Institution' in merged_df.columns:
    state_col = 'State of Institution'
elif 'State' in merged_df.columns:
    state_col = 'State'
else:
    state_col = None

if state_col:
    print(f"\nTop 10 states by number of institutions:")
    print(merged_df[state_col].value_counts().head(10))

Top 10 states by number of institutions:
State of Institution
CA    2240
NY    1393
TX    1386
PA    1109
FL    1066
OH     985
IL     828
NC     622
MA     531
VA     530
Name: count, dtype: int64

In [12]:
# Check distribution of institution types/sectors
if 'Sector of Institution' in merged_df.columns:
    sector_col = 'Sector of Institution'
elif 'Sector Name' in merged_df.columns:
    sector_col = 'Sector Name'
else:
    sector_col = None

if sector_col:
    print(f"\nDistribution by sector:")
    print(merged_df[sector_col].value_counts())

Distribution by sector:
Sector of Institution
2    6080
9    4060
4    4040
1    3544
6    1988
3     917
7     524
8     158
5     146
0      71
Name: count, dtype: int64

## 6. Save Column Mapping

Create a reference for the actual column names we'll use in feature engineering.

In [13]:
# Save all column names to a file for reference
with open('data/.cache/column_names.txt', 'w') as f:
    f.write("COLLEGE RESULTS COLUMNS:\n")
    f.write("="*80 + "\n")
    for col in college_results.columns:
        f.write(f"{col}\n")
    
    f.write("\n\nAFFORDABILITY GAP COLUMNS:\n")
    f.write("="*80 + "\n")
    for col in affordability_gap.columns:
        f.write(f"{col}\n")
    
    f.write("\n\nMERGED DATASET COLUMNS:\n")
    f.write("="*80 + "\n")
    for col in merged_df.columns:
        f.write(f"{col}\n")

print("Column names saved to data/.cache/column_names.txt")

Column names saved to data/.cache/column_names.txt

## 7. Next Steps

Based on this EDA, we need to:
1. Update the `features.py` module with the correct column names
2. Handle missing values appropriately
3. Identify race-specific graduation rate columns
4. Map affordability gap columns for standard students vs student-parents